version: '3'

services:
  flask:
    build:
      context: .
      dockerfile: flask_dockerfile
    volumes:
      - ./logs:/app/logs
      - ./passwords:/app/passwords
    expose:
      - "5000"

  nginx:
    build:
      context: .
      dockerfile: nginx_dockerfile
    ports:
      - "443:443"
    depends_on:
      - flask
    restart: always
    
    
    
